from typing import Any, Dict


DEFAULT_CONFIG: Dict[str, Any] = {
    "vosk_model_path": r"C:\Assistant\models\vosk-ru",
    "ollama_base_url": "http://localhost:11434",
    "ollama_model": "qwen3:8b",
    "wake_phrases": ["компьютер", "ассистент", "джарвис"],
    "command_listen_seconds": 7,
    "confirmation_listen_seconds": 5,
    "project_roots": [r"C:\Projects", r"C:\Work", r"C:\AI"],
    "folder_aliases": {
        "загрузки": r"E:\Downloads",
        "скачанные": r"E:\Downloads",
        "игры": r"E:\Games",
        "архив": r"D:\Archive",
        "проекты": r"C:\Projects",
        "работа": r"C:\Work",
        "ии": r"C:\AI",
        "ai": r"C:\AI",
        "модели": r"C:\AI",
        "временное": r"E:\Temp",
        "экспорты": r"E:\Exports",
        "бэкапы": r"D:\Backups",
        "медиа": r"D:\Media",
        "отчёты": r"C:\Assistant\reports",
        "отчеты": r"C:\Assistant\reports",
        "рабочий стол": r"%USERPROFILE%\Desktop",
    },
    "apps": {
        "vscode": "code",
        "visual studio code": "code",
        "код": "code",
        "steam": "steam://open/main",
        "стим": "steam://open/main",
        "браузер": "msedge",
        "edge": "msedge",
        "эдж": "msedge",
        "chrome": "chrome",
        "хром": "chrome",
        "obsidian": "obsidian",
        "обсидиан": "obsidian",
        "проводник": "explorer",
    },
    "voice": {"enabled": True, "rate": 185, "volume": 1.0},
    "confirmation": {
        "yes_phrases": ["да", "подтверждаю", "выполняй", "согласен", "разрешаю", "окей", "давай", "можно"],
        "no_phrases": ["нет", "отмена", "отмени", "не надо", "стоп", "нельзя", "не выполняй"],
    },
    "safe_actions": [
        "open_project",
        "open_folder",
        "open_app",
        "search_files",
        "disk_report",
        "storage_audit",
        "open_note",
        "append_inbox",
        "refresh_obsidian_inventory",
        "create_note",
        "obsidian_review",
        "set_project_alias",
        "prepare_sort_downloads",
        "confirm_sort_downloads",
        "cancel",
    ],
    "dangerous_actions": ["confirm_sort_downloads"],
    "pending_action_ttl_seconds": 900,
    "storage_policy": {
        "drives": {
            "C": "SSD 1TB: system, programs, active projects, AI, knowledge",
            "D": "HDD: archive, backups, media, old projects",
            "E": "SSD: games, downloads, temp, exports, active media",
        },
        "required_dirs": [
            r"C:\Projects",
            r"C:\Work",
            r"C:\AI",
            r"C:\Knowledge",
            r"D:\Archive",
            r"D:\Backups",
            r"D:\Media",
            r"E:\Downloads",
            r"E:\Games",
            r"E:\Temp",
            r"E:\Exports",
        ],
        "expected_aliases": {
            "загрузки": r"E:\Downloads",
            "скачанные": r"E:\Downloads",
            "игры": r"E:\Games",
            "архив": r"D:\Archive",
            "бэкапы": r"D:\Backups",
            "медиа": r"D:\Media",
            "временное": r"E:\Temp",
            "экспорты": r"E:\Exports",
        },
    },
    "downloads_sort_rules": {
        "Documents": [".pdf", ".doc", ".docx", ".txt", ".rtf", ".xlsx", ".xls", ".pptx", ".ppt", ".csv"],
        "Images": [".jpg", ".jpeg", ".png", ".webp", ".gif", ".bmp", ".svg"],
        "Video": [".mp4", ".mov", ".mkv", ".avi", ".webm", ".m4v"],
        "Audio": [".mp3", ".wav", ".flac", ".ogg", ".m4a"],
        "Archives": [".zip", ".rar", ".7z", ".tar", ".gz"],
        "Installers": [".exe", ".msi", ".dmg", ".iso"],
        "Temp": [".tmp", ".log", ".bak"],
    },
    "disk_report_roots": [r"C:\\", r"D:\\", r"E:\\"],
    "disk_report_top": 50,
    "disk_report_exclude_dirs": [
        r"C:\Windows",
        r"C:\Program Files",
        r"C:\Program Files (x86)",
        "node_modules",
        ".git",
        ".venv",
        "venv",
        "__pycache__",
    ],
    "search_max_results": 15,
    "obsidian": {
        "vault_path": r"C:\Knowledge\Brain",
        "inbox_path": r"C:\Knowledge\Brain\00_INBOX\Inbox.md",
        "inventory_note_path": r"C:\Knowledge\Brain\07_PC\Disks\Кандидаты для Obsidian.md",
        "inventory_csv_path": r"C:\Assistant\reports\obsidian_candidates.csv",
        "project_notes_dir": r"C:\Knowledge\Brain\02_PROJECTS",
        "software_notes_dir": r"C:\Knowledge\Brain\07_PC\Software",
        "folder_notes_dir": r"C:\Knowledge\Brain\07_PC\Folders",
        "review_dir": r"C:\Knowledge\Brain\01_DASHBOARDS",
        "auto_project_notes": True,
        "exclude_top_dirs": [
            "Windows",
            "Program Files",
            "Program Files (x86)",
            "ProgramData",
            "Users",
            "$Recycle.Bin",
            "System Volume Information",
            "Recovery",
            "Documents and Settings",
            "node_modules",
            ".venv",
            "venv",
            "__pycache__",
        ],
    },
    "project_aliases": {},
    "project_scan": {
        "max_depth": 2,
        "max_candidates_for_llm": 80,
        "cache_ttl_seconds": 600,
        "markers": [
            ".git",
            "README.md",
            "readme.md",
            "package.json",
            "pyproject.toml",
            "requirements.txt",
            "Cargo.toml",
            "go.mod",
            ".code-workspace",
        ],
    },
}
